<?php

namespace Database\Seeders;

use App\Models\Media;
use Illuminate\Database\Seeder;

class MediaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            'description' => "
                <p>Kau&ccedil;uk Nedir&nbsp;</p>

                <p>Kau&ccedil;uk, bitki &ouml;zsuyundan elde edilen bir lif. Doğal kau&ccedil;uk, ağa&ccedil;ların &ouml;zsuyundan yapılır.&nbsp;<a href='http://tekstilsayfasi.blogspot.com.tr/2012/12/sentetik-liflerin-tanimi-ve.html' target='_blank'>Sentetik&nbsp;</a>kau&ccedil;uk, kimyasal end&uuml;stri tarafından yağdan &uuml;retilir. Her iki t&uuml;r de &ccedil;ok y&ouml;nl&uuml; maddelerdir. Brezilya, Seylan, Meksika, Cava Adası, Orta ve Doğu Afrika&#39;da yetişir. Y&uuml;zlerce yıldan beri, doğal kau&ccedil;uk, kau&ccedil;uk ağacına &ccedil;izikler atmak suretiyle s&uuml;t halinde akan i&ccedil;indeki &ouml;zsuyu toplayarak, bu suyu kurumaya ve sertleşmeye bıraktıktan sonra &ccedil;eşitli işlemler kullanılarak elde edilmektedir. 20. y&uuml;zyıl boyunca, kimyadaki ilerlemeler, yağdaki kau&ccedil;uğun kullanılarak suni versiyonunun yapılmasına imk&acirc;n tanıdı.<br />
                <br />
                Kau&ccedil;uk, bug&uuml;nk&uuml; end&uuml;strinin &ouml;nemli maddelerinden biridir. Motorlu ve motorsuz taşıtların&nbsp;<a href='http://tekstilsayfasi.blogspot.com.tr/2012/11/lastik-nedir-araba-ve-tasit-lastikleri.html' target='_blank'>tekerlekleri</a>, &ccedil;eşitli yağmurluklar, ayakkabılar, elektrik&ccedil;ilikte en &ouml;nemli izoleler, d&uuml;ğme, tarak, kalem gibi maddeler, yapıştırma sol&uuml;syonları, vernikler, kau&ccedil;uğun end&uuml;striye uygulanma şekilleridir. Doğal kau&ccedil;uğun, bu kadar &ccedil;ok kullanılması ve ihtiyaca cevap verememesi sebebiyle; kau&ccedil;uğu ucuz ve bol miktarlarda elde edebilmek i&ccedil;in 1906 yılında Almanlar tarafından sentetik (yapay) kau&ccedil;uk elde edilmiştir. Kau&ccedil;uk aslında bir ağa&ccedil; adıdır. Bu ağacın kendisinden ve &ouml;zsuyu olan&nbsp;<a href='http://tekstilsayfasi.blogspot.com.tr/2012/11/lateks-nedir.html' target='_blank'>lateks</a>inden elde edilen maddeler end&uuml;stride kullanım sahası bulmuştur. Son yıllarda tabii kau&ccedil;uğun yanı sıra sentetik kau&ccedil;uğun da yaygınlaşması ile pek &ccedil;ok kau&ccedil;uk t&uuml;r&uuml; ortaya &ccedil;ıkmıştır. Her yıl &uuml;retilen milyonlarca ton kau&ccedil;uğun b&uuml;y&uuml;k bir kısmı sentetiktir.<br />
                <br />
                Kau&ccedil;uğun en &ouml;nemli &ouml;zelliği y&uuml;ksek bir elastikiyete sahip olması, yani eski haline d&ouml;nebilen bir uzayabilirliğinin olmasıdır. Kau&ccedil;uk işleme end&uuml;strisinin gelişmesinin ve kau&ccedil;uğun hemen her sekt&ouml;rde kullanılmasının temelinde de bu vardır. Kau&ccedil;uk, daha &ccedil;ok s&uuml;tleğengiller (Euphorbiaceae) familyası bitkilerinde, ayrıca compositae, apocynaceae ve asclepiadaceae familyaları bitkilerinde bulunan l&acirc;teksin (bitkilerde s&uuml;t g&ouml;r&uuml;n&uuml;m&uuml;nde &ouml;zsu) kurutulmasıyla elde edilen &uuml;r&uuml;nd&uuml;r. Kau&ccedil;uğun adı, Amazon b&ouml;lgesi yerlilerinin dilinden gelir (caa-o-cu - ağlayan ağa&ccedil;). Brezilya&#39;da eskiden kurutulmuş bir bal&ccedil;ık kalıp &uuml;st&uuml;nde kat kat s&uuml;r&uuml;len kau&ccedil;uğun pıhtılaştırılması ile ayakkabı yapılıyordu. Lateksin bezler arasında kurutulması ile de, su ge&ccedil;irmez bezler &uuml;retiliyordu. Kau&ccedil;uktan ilk olarak 1530&#39;larda bahsedilmeye başlandı. Daha &ouml;nceleri bilinmiyordu. Modern kau&ccedil;uk imalat end&uuml;strisi ise, kau&ccedil;uğun k&uuml;k&uuml;rtle sertleştirilmesi (vulkonizasyon) işlemiyle başlamıştır (1839). Bu end&uuml;strinin gelişmesi, kau&ccedil;uğun hammaddesinin işlenerek bir&ccedil;ok yerde kullanılmasına sebep oldu. 1839-1840 yıllarında Amerika Birleşik Devletlerinde Goodyear, İngiltere&#39;de Hancock, kau&ccedil;uğu k&uuml;k&uuml;rtle birleştirdiler ve sıcakta yapışkan olmayan, soğukta esnekliğini kaybetmeyen bir madde elde ettiler. Bug&uuml;nk&uuml; lastik tekerlek sanayinin temeli atıldı.<br />
                &nbsp;</p>
                
                <p>Kau&ccedil;uk Tarih&ccedil;esi<br />
                Konuşma dilimizde &#39;&#39;lastik&#39;&#39; diye adlandırdığımız şey, ham maddesi tropikal ağa&ccedil;lardan elde edilen bitkisel bir &uuml;r&uuml;nd&uuml;r. Bu ağa&ccedil;lardan Brezilya kau&ccedil;uk ağacı (Hevea brasiliensis) adı veri&shy;len bir &ccedil;eşidi ticari &ouml;nem taşır. Brezilya&#39;nın Amazon b&ouml;lgesi ormanlarına has bir bitki olan bu ağa&ccedil;, sonraları Uzak Doğu&#39;ya da g&ouml;t&uuml;r&uuml;lm&uuml;ş, iklim şartları aynı olan bu b&ouml;lgelerde de kolay&shy;lıkla &uuml;retilmiştir. 20 - 30 m. boyunda, yuvarlak g&ouml;vdeli, yaprakları tepesinde k&uuml;melenmiş Brezilya kau&ccedil;uk ağacı, humusu bol yaş topraklarda yetişir. Kau&ccedil;uğu ilk olarak (1940&#39;lı yıllarda) tam anlamıyla g&uuml;nl&uuml;k yaşamımıza sokan kişi kau&ccedil;uğun babası olarak da bilinen Jonhson Goodyear&#39;dir. Ham kau&ccedil;uğa lateks denir.&nbsp;<a href='http://tekstilsayfasi.blogspot.com.tr/2013/01/pamuk-fiziksel-kimyasal-ozellikleri.html' target='_blank'>Pamuk</a>&nbsp;veya viskonla karıştırılarak, kemer korse, lastik &ccedil;orap (varis &ccedil;orabı) yapımında kullanılır. Kau&ccedil;uk, giysi, hortum ve lastik yapmak i&ccedil;in esnek bir maddeye d&ouml;n&uuml;şt&uuml;r&uuml;lebilir. Kau&ccedil;uğun emici &ouml;zellikleri, onu otomobil s&uuml;spansiyonunda kullanışlı madde yapar. Kau&ccedil;uk aynı zamanda end&uuml;striyel maddelerin titreşimlerini de azaltır. Ayrıca kau&ccedil;uktan su ge&ccedil;irmezlik&nbsp;<a href='http://tekstilsayfasi.blogspot.com.tr/2014/01/apre-nedir.html' target='_blank'>apre</a>sinde de faydalanılır. Kau&ccedil;uk suya dayanıklı olduğu i&ccedil;in, dalgı&ccedil; giysilerinde, yağmurluklarda kullanılır. Kau&ccedil;uk iyi bir elektrik yalıtkanıdır ve genellikle elektrik tellerini kaplamada kullanılır. Kau&ccedil;uk, milyonlarca hava kabarcığından oluşan k&ouml;p&uuml;k hale d&ouml;n&uuml;şt&uuml;r&uuml;lebilir. Bu k&ouml;p&uuml;ğe kalıp verilip, s&uuml;nger ve yastık gibi &ccedil;ok sayıda hafif &uuml;r&uuml;n elde edilebilir. Kau&ccedil;uğun elde edilmesine, ilk olarak Brezilya&#39;da başlanmıştır. 19. y&uuml;zyıl başlarında yıllık &uuml;retim 30 tondu. Bug&uuml;n ise sentetik yollarla elde edilen 1 milyon tondan fazla suni kau&ccedil;uk dışında D&uuml;nya doğal kau&ccedil;uk &uuml;retimi yılda 4 milyon tonu bulur. Y&uuml;zyıla yakın bir s&uuml;reden beri kau&ccedil;uk &uuml;retimi, teknik ve end&uuml;stri alanındaki gelişmelerle birlikte y&uuml;r&uuml;m&uuml;ş, bunların ilerlemesine yeni bir hamle vermiştir. Esnekliği, aşınmaya dayanıklılığı, su ge&ccedil;irmezliği kau&ccedil;uğu, modern end&uuml;strinin &ouml;zellikle mekanik ulaştırma tekniğinin en g&ouml;zde maddelerinden biri durumuna getirmiştir.</p>
                
                <p>&nbsp;</p>
                
                <p>Kau&ccedil;uk Tarihi Kronolojisi;&nbsp;</p>
                
                <p>1493 - Amerika&#39;ya yaptığı ikinci yolculuk sırasında Kristof Kolomb, Haiti Adası&#39;nda yerlilerin acayip bir topla oynadıklarını g&ouml;rd&uuml;. Bu &ouml;yle bir toptu ki yere vurduk&ccedil;a zıplıyordu.</p>
                
                <p>1521 - Meksika&#39;nın İspanyol egemenliği altında bulunduğu yıl&shy;larda bazı ispanyol gezginleri, yerlilerin elastik bir madde kullan&shy;makta olduklarını g&ouml;rm&uuml;şlerdi. Avrupa&#39;da da bunlara ait &ccedil;e&shy;şitli s&ouml;ylentiler dolaşmaya başlamıştı. Yerlilerin&nbsp;<a href='http://tekstilsayfasi.blogspot.com.tr/2012/12/boyar-madde-ve-renk-bilgisi.html' target='_blank'>renk</a>&nbsp;renk t&uuml;yleri, &shy;bir bitkiden &ccedil;ıkardıkları s&uuml;te benzeyen beyazımsı maddeyle v&uuml;cutlarına yapıştırdıkları, b&ouml;ylece b&uuml;y&uuml;c&uuml; kılığına b&uuml;r&uuml;nd&uuml;k&shy;leri s&ouml;yleniyordu. İ&ccedil;ine ayaklarını batırıp &ccedil;ıkardıkları bu s&uuml;t gibi maddenin kuruduktan sonra &ccedil;arığa benzer bir &ccedil;eşit ayakkabı bi&ccedil;imini aldığı da dolaşan s&ouml;ylentiler arasındaydı.</p>
                
                <p>1735 - Charles de la Condamine adında bir Fransız, hi&ccedil;bir Av&shy;rupa&#39;lının karşılaşmadığı bu acayip bitkilerin esrarını &ccedil;&ouml;zmek &uuml;zere Amazon ormanlarına doğru yola &ccedil;ıktı. Yerliler ağaca &#39;g&ouml;z yaşı&#39; anlamına gelen &#39;heve&#39; yahut &#39;cao ochu&#39; adını veriyorlardı. Ser&uuml;venle dolu bir yolculuktan sonra de la Condamine, bu esrarengiz ağacı buldu. Kabuğunu keserek &ccedil;ıkardığı s&uuml;t&uuml; (Iateks = kau&ccedil;uk) kurutup bazı modeller yaptı ve Fransa&#39;ya yolladı. O &ccedil;ağın bilim adamları bu acayip cevheri inceleyip &ccedil;&ouml;z&uuml;mlemeye koyuldular.</p>
                
                <p>1763 - Birka&ccedil; Fransız kimyacısı cevheri trebentin yağı ve etere batırıp eritmeyi başardılar. Bu yıllarda lateksin, lastik adı altın&shy;da, m&uuml;rekkep lekelerini kağıt &uuml;zerinden &ccedil;ıkarmak i&ccedil;in silgi ola&shy;rak kullanılmaya başlandığı g&ouml;r&uuml;l&uuml;r.</p>
                
                <p>1793 - Peal adında bir İngiliz, kau&ccedil;uğu trebentin i&ccedil;inde eriterek su ge&ccedil;irmez bir madde yapma patentini aldı.</p>
                
                <p>1823 - Charles Macintosh adında İsko&ccedil;ya&#39;lı bir kimyacı, su ge&shy;&ccedil;irmez maddelerin yapım metodunu geliştirdi ve lastik eşya yapmak &uuml;zere ilk fabrikayı kurdu. Bug&uuml;n bile İngiltere&#39;de &#39;mackintosh&#39; adıyla anılan su ge&ccedil;irmez&nbsp;<a href='http://tekstilsayfasi.blogspot.com.tr/2015/10/hangi-tur-kumaslar-kis-aylari-icin.html' target='_blank'>pardes&uuml;ler</a>&nbsp;(muşamba) yapılır. Bu ilk lastik eşyanın bazı kusurları vardı: sıcak havaya dayanamayıp eriyor ve &ccedil;abuk eskiyordu. Soğuk havalarda ise sertleşip esnekliğini kaybediyordu.</p>
                
                <p>1839 - Charles Goodyear adındaki Amerika&#39;lının bir raslantı sonucu bulduğu sistem, lastik sanayinde devrim yarattı. Goodyear, lateksi ısıtıp k&uuml;k&uuml;rtle işleyerek daha elastiki ve dayanıklı bir duruma getirdi. B&ouml;ylece kau&ccedil;uğa hava şartlarından etkilenmez bir nitelik kazandırdı. Bu işleme, vulkanize etmek denir. K&uuml;&shy;k&uuml;rtleme işlemi, kau&ccedil;uğun kullanılış alanlarını genişlettiği gibi fiyatlarını da artırdı. Kau&ccedil;uk yıllık &uuml;retim 30 ton&shy;dan hızlıca 350 tona y&uuml;kseldi.</p>
                
                <p>1873 - İngiltere h&uuml;k&uuml;meti bir d&ouml;nem iklim y&ouml;n&uuml;nden Amazon ormanlarına benzerlik g&ouml;steren s&ouml;m&uuml;rgelerinde kau&ccedil;uk ağa&ccedil;ları yetiştirmeyi d&uuml;ş&uuml;nd&uuml;. Farris adında biri, bu ağa&ccedil;ların tekelini bırakmak istemeyen Brezilya H&uuml;k&uuml;meti g&uuml;mr&uuml;ğ&uuml;nden sıyrılarak 2000 kadar Brezilya kau&ccedil;uk ağacı tohumunu İngiltere&#39;ye ka&ccedil;ırdı. Ama Kalk&uuml;ta&#39;ya getirilen tohumlardan ancak bir d&uuml;zinesi tuttuğu gibi bunlardan s&uuml;rg&uuml;n veren altı tanesi de kuruyup gitti. Bir s&uuml;re sonra Henry Wickham adında bir İngiliz, Brezilya&#39;dan 70.000 tohum ka&ccedil;ırdı. Seylan&#39;a g&ouml;t&uuml;r&uuml;len bu tohumlardan 2.000 tanesi iklime alışarak gelişti. B&uuml;t&uuml;n bu olaylar bir sır perdesi arka&shy;sında cereyan etti.</p>
                
                <p>1885 - Afrika&#39;da yetişen, Lastik ağacı (Ficus elastica) adlı bir ağa&ccedil;tan da kau&ccedil;uk elde edildi. B&ouml;ylece yıllık &uuml;retim 4.000 tona ulaşmış oldu.</p>
                
                <p>1907 - Hi&ccedil; kimsenin haberi olmaksızın Seylan&#39;da gizli gizli ye&shy;tiştirilen Brezilya kau&ccedil;uk ağa&ccedil;larının tohumları Malezya&#39;ya aktarıldı. H. N. Ridley adındaki İngiliz botanik&ccedil;isinin &ccedil;alışmalarıyla elde edilen başarı sonucu yılda 6.000 tonluk kau&ccedil;uk, D&uuml;nya pazarlarına s&uuml;r&uuml;ld&uuml;. Bu, kolay ve &ccedil;abuk kazan&ccedil;lar sağlayan Brezilya ve Afrika kau&ccedil;uk t&uuml;ccarlarının sonu oldu. Holanda&#39;lıların Endonezya, Amerika&#39;lıların Liberya ve Brezilya, Fransız&#39;ların &Ccedil;in Hindistanı&#39;nda kurdukları kau&ccedil;uk ağacı &ccedil;iftlikleriyle D&uuml;nya kau&ccedil;uk &uuml;retiminde uluslararası bir yarış başladı. Motorlu kara ara&ccedil;larının hızla gelişmesi lastik&nbsp;<a href='http://tekstilsayfasi.blogspot.com.tr/2012/11/lastik-nedir-araba-ve-tasit-lastikleri.html' target='_blank'>tekerlek</a>&nbsp;piyasasını iyice canlandırdı. Kau&ccedil;uk &uuml;retimi başlı başına bir tarım end&uuml;strisi halini aldı. Daha y&uuml;ksek verimli ağa&ccedil; yetiştirilmesi ve tohumla&shy;rın ıslahı yoluna gidildi. Gerek &ccedil;iftliklerin işletimi, gerek lateksin toplanmasında daha ekonomik metodlar ortaya konuldu. Bug&uuml;n ileri end&uuml;stri &uuml;lkelerinde sentetik kau&ccedil;uk yapımı gittik&ccedil;e artmakla birlikte Brezilya kau&ccedil;uk ağa&ccedil;larından &ccedil;ıkarılan doğal kau&ccedil;uk hala &ouml;n planda gelmektedir. D&uuml;nya&#39;da Kau&ccedil;uk &Uuml;retiminde Malezya, Endonezya ve Tayland başta olmak &uuml;zere G&uuml;neydoğu Asya &Uuml;lkeleri s&ouml;z sahibidir.</p>
            ",
        ];

        Media::create($data);
    }
}
